#! /bin/bash

set -e
#### Cross compiler ####################################################
CROSS_COMPILE_PATH=/opt/cross

#### Target OS #########################################################
#TARGET_OS="Ubuntu-18.04hf"
TARGET_OS="Ubuntu-16.04hf"

#### Target Board ######################################################
#TARGET_BOARD="IMX8MM_EVK"
#TARGET_BOARD="IMX8MM_EVK_M4"
#TARGET_BOARD="IMX8MM_CSE"
TARGET_BOARD="IMX6_PICO"

#### Default Define ####################################################
KERNEL_DEFAULT_CONFIG=imx_v8_defconfig
BUILD_GPU_VIV_DRIVER_MODULE="no"

TOP=`pwd`
OUT=${TOP}/out

########################################################################


case "${TARGET_OS}" in
	"Ubuntu-18.04hf")
		# Ubuntu 18.04
		echo "Build Kernel for Ubuntu 18.04 hf"
		export ARCH=arm64
		export CROSS_COMPILE=${CROSS_COMPILE_PATH}/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
		;;
	"Ubuntu-16.04hf")
		# Ubuntu 16.04
		echo "Build Kernel for Ubuntu 16.04 hf"
		export ARCH=arm
		export CROSS_COMPILE=arm-linux-gnueabihf-
		;;
	*)
		echo "Please set the target OS."
		exit 1
		;;
esac

case "${TARGET_BOARD}" in
	"IMX8MM_EVK" )
		TARGET_SOC=imx8mm
		KERNEL_PROJECT_CONFIG=arch/arm64/configs/imx_v8_defconfig
		KERNEL_DTB=imx8mm-evk
		;;
	"IMX8MM_EVK_M4" )
		TARGET_SOC=imx8mm
		KERNEL_PROJECT_CONFIG=rtx/configs/rtx-imx8mm-evk_defconfig
		KERNEL_DTB=fsl-imx8mm-evk-m4
		;;
	"IMX8MM_CSE" )
		TARGET_SOC=imx8mm
		KERNEL_PROJECT_CONFIG=rtx/configs/rtx-imx8mm-cse_defconfig
		KERNEL_DTB=rtx-imx8mm-cse
		;;
	"IMX6_PICO" )
		KERNEL_DEFAULT_CONFIG=imx_v7_defconfig
		TARGET_SOC=imx6q
		KERNEL_PROJECT_CONFIG=rtx/configs/rtx-imx6q-pitx-b21_defconfig
		KERNEL_LOADADDR=0x10008000
		KERNEL_DTB=rtx-imx6q-pitx-b21
		;;
	*)
		echo "Please set the target board."
		exit 1
		;;
esac

KERNEL_VERSION=`make kernelversion`

function build_dir()
{
	for dir_item in out rtxconfig
	do
		if [ ! -d ${dir_item} ] ; then
			mkdir -p ${dir_item}
		fi
	done
}

function configure()
{
	unset LDFLAGS
	if [ -z "${KERNEL_DEFAULT_CONFIG}" ] ; then
		echo "Please set the default configure file."
		exit 1
	fi
	
	if [ ! -z "${1}" ] ; then
		echo "Use the currently configure file (${KERNEL_DEFAULT_CONFIG})."
		make distclean
		make ${1}
	else
		if [ ! -f .config ] ; then
			if [ -z "${KERNEL_PROJECT_CONFIG}" ] ; then
				echo "The project configure file (${KERNEL_PROJECT_CONFIG}) do not set."
				echo "Use the default configure file (${KERNEL_DEFAULT_CONFIG})."
				make ${KERNEL_DEFAULT_CONFIG}
			else
				if [ -f ${KERNEL_PROJECT_CONFIG} ] ; then
					echo "Use the project configure file (${KERNEL_PROJECT_CONFIG})."
					cp ${KERNEL_PROJECT_CONFIG} .config
				else
					echo "The project configure file (${KERNEL_PROJECT_CONFIG}) is not exist."
					echo "Use the default configure file (${KERNEL_DEFAULT_CONFIG})."
					make ${KERNEL_DEFAULT_CONFIG}
				fi
			fi
		else
			echo "Use the currently configure file (.config)"
		fi
	fi
}

function build_kernel()
{
	case "${TARGET_BOARD}" in
		"IMX8MM_EVK" )
			make -j8 
	
			if [ -f arch/arm64/boot/Image ] ; then
				cp -f arch/arm64/boot/Image out/.
				cp arch/arm64/boot/dts/freescale/$KERNEL_DTB.dtb out/.
			fi
			;;
		"IMX6_PICO" )
			if [ -z "${KERNEL_LOADADDR}" ] ; then
				make uImage -j8
			else
				make uImage -j8 LOADADDR=${KERNEL_LOADADDR}
			fi
	
			if [ -f arch/arm/boot/uImage ] ; then
				cp -f arch/arm/boot/uImage out/.
				if [ ! -z "${KERNEL_VERSION}" ] ; then
					cp -f arch/arm/boot/uImage out/uImage-${KERNEL_VERSION}
				fi
			fi
	
			if [ ! -z "${KERNEL_DTB}" ] ; then
				make ${KERNEL_DTB}.dtb
				cp arch/arm/boot/dts/${KERNEL_DTB}.dtb out/.
				if [ ! -z "${KERNEL_VERSION}" ] ; then
					cp arch/arm/boot/dts/${KERNEL_DTB}.dtb out/${KERNEL_DTB}-${KERNEL_VERSION}.dtb
				fi
			fi
			;;
		*)
			echo "Please set the target board."
			exit 1
			;;
	esac
}

function build_dtb()
{
	case "${TARGET_BOARD}" in
		"IMX8MM_EVK" )
			if [ ! -z "${KERNEL_DTB}" ] ; then
				cp arch/arm64/boot/dts/freescale/$KERNEL_DTB.dtb out/.
			fi
			;;
		"IMX6_PICO" )
			if [ ! -z "${KERNEL_DTB}" ] ; then
				make ${KERNEL_DTB}.dtb
				cp arch/arm/boot/dts/${KERNEL_DTB}.dtb out/.
				if [ ! -z "${KERNEL_VERSION}" ] ; then
					cp arch/arm/boot/dts/${KERNEL_DTB}.dtb out/${KERNEL_DTB}-${KERNEL_VERSION}.dtb
				fi
			fi
			;;
		*)
			echo "Please set the target board."
			exit 1
			;;
	esac
}

function build_imx_firmware()
{
	case "${TARGET_SOC}" in
		"imx6q")
			if [ ! -d rtx/imx6-libs ] ; then
				break ;
			fi
			if [ ! -f rtx/imx6-libs/firmware-imx-5.4.bin ] ; then
				break ;
			fi
			if [ -d .tmp_build ] ; then
				rm -rf .tmp_build
			fi
			mkdir -p .tmp_build
			
			cp rtx/imx6-libs/firmware-imx-5.4.bin .tmp_build/.
			cd .tmp_build
			chmod +x firmware-imx-5.4.bin
			./firmware-imx-5.4.bin --auto-accept --force
			cd ${TOP}
			mkdir -p out/lib/firmware/imx
			cp -rfv .tmp_build/firmware-imx-5.4/firmware/* out/lib/firmware/
			mv out/lib/firmware/epdc/ out/lib/firmware/imx/epdc/
			mv out/lib/firmware/imx/epdc/epdc_ED060XH2C1.fw.nonrestricted out/lib/firmware/imx/epdc/epdc_ED060XH2C1.fw

			#find out/lib/firmware -type f -exec chmod 644 '{}' ';'
			#find out/lib/firmware -type f -exec chown root:root '{}' ';'

			# Remove files not going to be installed
			find out/lib/firmware/ -name '*.mk' -exec rm '{}' ';'
			rm -rf .tmp_build
		;;
	esac
}

function build_gpu_viv_module()
{
	if [ ${BUILD_GPU_VIV_DRIVER_MODULE} == "yes" ] ; then
		case "${TARGET_SOC}" in
			"imx6q")
				cd ${TOP}
				
				if [ ! -d rtx/imx6-libs ] ; then
					break ;
				fi
				if [ ! -f rtx/imx6-libs/kernel-module-imx-gpu-viv-6.2.2.p0.tar.gz ] ; then
					break ;
				fi
				if [ -d .tmp_build ] ; then
					rm -rf .tmp_build
				fi
				mkdir -p .tmp_build
				cd .tmp_build
				
				if [ ! -f .extract ] ; then
					tar xzvf ${TOP}/rtx/imx6-libs/kernel-module-imx-gpu-viv-6.2.2.p0.tar.gz
					touch .extract
				fi
				cd kernel-module-imx-gpu-viv-6.2.2.p0
				KERNEL_SRC=${TOP} make
				KERNEL_SRC=${TOP} make DEPMOD=/bin/true INSTALL_MOD_PATH=${TOP}/out modules_install
				cd ${TOP}
				rm -rf .tmp_build
			;;
		esac
	fi
}

# Main function

# Build the necessary directions
build_dir

# 
case "${1}" in
	"info")
		echo "ARCH		          = ${ARCH}"
		echo "CROSS_COMPILE_PATH          = ${CROSS_COMPILE_PATH}"
		echo "CROSS_COMPILE               = ${CROSS_COMPILE}"
		echo "TARGET_OS                   = ${TARGET_OS}"
		echo "TARGET_BOARD                = ${TARGET_BOARD}"
		echo "TARGET_SOC                  = ${TARGET_SOC}"
		echo "KERNEL_PROJECT_CONFIG       = ${KERNEL_PROJECT_CONFIG}"
		echo "KERNEL_VERSION              = ${KERNEL_VERSION}"
		echo "KERNEL_DEFAULT_CONFIG       = ${KERNEL_DEFAULT_CONFIG}"
		echo "KERNEL_DTB                  = ${KERNEL_DTB}"
		;;
	"all")
		if [ -d out ]; then
			rm -rf out; sync;
		fi

		mkdir -p out
		
		configure ${2}
		
		build_kernel
		
		make modules -j8
		make DEPMOD=/bin/true INSTALL_MOD_PATH=out modules_install
		make INSTALL_HDR_PATH=out headers_install	
		cd out
		tar cjvf lib.tar.bz2 lib
		cd ..
		;;
	"config")
		configure ${2}
		;;
	"menuconfig")
		configure ${2}
		make menuconfig
		;;
	"diff")
		diff .config ${KERNEL_PROJECT_CONFIG}
		;;
	"save")
		if [ -f .config ] ; then
			cp .config ${KERNEL_PROJECT_CONFIG}
		fi
		;;
	"save-as")
		if [ -f .config ] ; then
			if [ -z "${2}" ] ; then
				echo "cmd save-as [filename]"
			else
				cp .config rtxconfig/${2}
			fi
		fi
		;;
	"load")
		if [ -z "${2}" ] ; then
			echo "cmd load [filename]"
		else
			cp rtxconfig/${2} .config
		fi
		;;
	"uImage")
		configure ${2}
		build_kernel
		;;
	"dtb")
		configure ${2}
		build_dtb
		;;
	"clean")
		make clean
		;;
	"distclean")
		make distclean
		rm -rf out
		;;
	*) 
		echo "${0} [all/config/menuconfig/saveconfig/uImage/install/clean/distclean]"
		exit 1
		;;
esac
