#
# Makefile for RTC class/drivers.
#

ccflags-$(CONFIG_RTC_DEBUG)	:= -DDEBUG

# Retronix EFM32 MCU
obj-$(CONFIG_RTC_DRV_EFM32_BISHOP)	+= rtc-efm32-bishop.o
obj-$(CONFIG_RTC_DRV_EFM32_A6)		+= rtc-efm32-a6.o
obj-$(CONFIG_RTC_DRV_EFM32_Q7)		+= rtc-efm32-q7.o
obj-$(CONFIG_RTC_DRV_EFM32_ADLINK)	+= rtc-efm32-adlink.o
obj-$(CONFIG_RTC_DRV_EFM32_PICO)	+= rtc-efm32-pico.o
obj-$(CONFIG_RTC_DRV_EFM32_CSE)		+= rtc-efm32-cse.o
